// Generates packages/chain/src/generated.ts from the compiled contracts (contracts/out) and
// deployments/arc-testnet.json, so the app always uses the exact ABIs and addresses that are deployed.
// Run: pnpm gen   (after `forge build` in contracts/)
import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("..", import.meta.url).pathname;
const abi = (file, name) => JSON.parse(readFileSync(`${root}contracts/out/${file}/${name}.json`, "utf8")).abi;
const dep = JSON.parse(readFileSync(`${root}deployments/arc-testnet.json`, "utf8"));

const out = `// GENERATED by scripts/gen-chain.mjs. Do not edit by hand.
export const deployment = ${JSON.stringify(
  {
    chainId: dep.chainId,
    block: dep.block,
    usdc: dep.usdc,
    payeeRegistry: dep.contracts.PayeeRegistry.address,
    mandateFactory: dep.contracts.MandateFactory.address,
    mandateImplementation: dep.contracts.MandateImplementation.address,
  },
  null,
  2,
)} as const;

export const payeeRegistryAbi = ${JSON.stringify(abi("PayeeRegistry.sol", "PayeeRegistry"))} as const;
export const mandateAbi = ${JSON.stringify(abi("Mandate.sol", "Mandate"))} as const;
export const mandateFactoryAbi = ${JSON.stringify(abi("MandateFactory.sol", "MandateFactory"))} as const;
`;
writeFileSync(`${root}packages/chain/src/generated.ts`, out);
console.log("wrote packages/chain/src/generated.ts");
